### ISSUE TITLE
[ SEO ] Meta Description tag and alt attributes of 29 images are absent

### ISSUE THREAD

**Issue by AnirudhPanda** [Bloggify/Bloggify#140]
- Your page appears to be missing a meta description tag. A meta description is important for search engines to understand the content of your page and is often shown as the description text blurb in search results.
- You have images on your page that are missing ALT attributes.

We found 29 images on your page and 29 of them are missing the attribute. Affects On-Page SEO

**Comment by IonicaBizau** [comment]
Thanks for the report. The `og:image` should work now on the homepage.
What are the pages you are referring to?
